### PR TITLE
TFL-538: Propose module-based folder structure

### PR DESCRIPTION
**Pull request by kolyamba2105**

### CODE REVIEW

**Review by brezzhnev — APPROVED** [review]
I like this. 

The only thing I'd change is to create a separate document describing a folder structure for mid-size projects or bigger.

So we have guidelines for both types of projects with corresponding approaches.

**Comment by kolyamba2105** [comment]
> I like this.
> 
> The only thing I'd change is to create a separate document describing a folder structure for mid-size projects or bigger.
> 
> So we have guidelines for both types of projects with corresponding approaches.

I think it makes sense to apply this approach in our current project first. This way we will be able to define our guidelines and principles in a more concrete way. At this moment this document is pretty raw and I think we will modify/add some info in the future anyway. WDYT?

**Review by non25 — APPROVED** [review]

**Comment by rec25** [comment]
@kolyamba2105

- What do the aliases look like? `@order/utils`, `@order/components`? Are you going to save the aliases `@components` or it will be `@common/components`?
- Is `assets/images` for common usage or the images related to the module should be there?
- The same file names are going to make debugging more difficult from my perspective. You will get something like this:
  - https://tppr.me/p0VZi
  - https://tppr.me/Euqmo
Note, if an error happens, you will get `actions.ts` in the browser console. Then you have to investigate what `actions.ts` exactly triggered.
- Is there an advantage to use `SubModule.module.scss` instead of `SubModule.scss`?
- Are you going to use CSS modules?

**Comment by kolyamba2105** [comment]
> @kolyamba2105
> 
> * What do the aliases look like for modules? `@order/utils`, `@order/components`? Are you going to save the aliases `@components` or it will be `@common/components`?
> * Is `assets/images` for common usage or the images related to the module should be there?
> * The same file names are going to make debugging more difficult from my perspective. You will get something like this:
>   
>   * https://tppr.me/p0VZi
>   * https://tppr.me/Euqmo
>     Note, if an error happens, you will get `actions.ts` in the browser console. Then you have to investigate what `actions.ts` exactly triggered.
> * Is there the naming advantage to use `SubModule.module.scss` instead of `SubModule.scss`?
> * Are you going to use CSS modules?

Imports will look like this:

```ts
import { SomeComponent, someUtil } from '@common';
```

I didn't mention that in this file, since we only discuss folder structure here.

Regarding assets and images - whatever they are going to be used for. If some image is module-specific, then it makes sense to store it in that module. Otherwise it can be in common module.

Regarding searching for files - I can't really see any difference against our current project structure:

Screen Shot 2022-02-22 at 1 50 10 PM

Isn't this search result similar? If you specify what you're search for (for ex. `order actions`) you will get what you need in both folder structures.

Regarding console error messages - you will look into file content in the console, right? So you will be able to determine which file is it, won't you? So does the really make things harder to debug?

Regarding styles - there's no advantage in naming `SubModule.module.scss` unless we don't use CSS modules. We are still not sure about what way of writing CSS we'll choose, but the main idea is to scope `everything` to a specific module - including `styles`, `components`, `utils` etc.

**Comment by rec25** [comment]
- Related to CSS modules - if you import the styles to the CSS module, you extend all styles to this module. I will provide the details if you decide to use CSS modules.
- If Tailwind is ok with CSS modules, this is ok then. But if it isn't, how would you combine Tailwind class names with modules?
- Related to search, you find the folder with files, but my point is the final file. You can definitely define the file like `order.actions.ts`, `app.constants.ts`, but not `constants.ts`, `actions.ts`. There are examples how it can look like: 
  - https://tppr.me/YNm9e > https://tppr.me/kVDsZ > https://tppr.me/47zGr - what exactly `Skeleton.scss`? What Layout? Probably, you need some time to find it. But another developer has to spend more time to find out if he is new with your module.
  - I made the error in some `Header` - https://tppr.me/q0aW6. Where is that Header component? How many trace lines do I need to analyze to understand in what module it happend?

This is my concept of the duplicated scope naming like `OrderHeader`, `order.actions` etc.

Other changes seem very useful 👍🏻

**Comment by non25** [comment]
> Related to CSS modules - if you import the styles to the CSS module, you extend all styles to this module. I will provide the details if you decide to use CSS modules.

You just don't import anything that generates rules on its own in component's style file. Only variables, mixins, functions, etc. Just as described in the tree (shared.scss).

> If Tailwind is ok with CSS modules, this is ok then. But if it isn't, how would you combine Tailwind class names with modules?

Tailwind classes could be applied to the selector in any css file using [@apply directive](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply).

> Related to search, you find the folder with files, but my point is the final file. You can definitely define the file like order.actions.ts, app.constants.ts, but not constants.ts, actions.ts. There are examples how it can look like.

I've been working on 16mb src dir module-based react project for almost a year. I've never experienced any problems with module-based structure.

I've been able to just jump straight in and develop a module of a considerable size in a nice, isolated way. Structure was huge, but familiar and predictable.

The fewer the connection points between modules, the easier it is to add or delete a module. Ideally that's just a single import point with module-controlled routing.

Regarding errors, in most cases errors are coming from the module you are working on. And you are already sitting in the module tree, so there's no problems to find the file.

I believe there's a configuration, which would allow you to fuzzy search from the module root, not application root.

Anyway, at some point your way of searching just won't work, regardless of the file structure.

The problems I have with global css and global namespace for files is that it will be exponentially harder to think of unique names to be able to fuzzy-search to them from the root of the application.

Why do we need to burden developers with this?

Even redux authors suggest that it's easier to maintain module/feature-based structure: [link](https://redux.js.org/style-guide/style-guide#structure-files-as-feature-folders-with-single-file-logic).

To conclude, I fail to see how your points will negatively affect the development, but it's obvious to me how module-based structure is familiar and just makes sense for medium-large project and won't require explaining at all in case we'll need to onboard more developers.

**Comment by rec25** [comment]
> Tailwind classes could be applied to the selector in any css file using [@apply directive](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply).

Ok, it makes sense.

**Comment by brezzhnev** [comment]
I'd suggest we move forward with this. Overall I think the pros definitely outweigh the cons, and I don't think we will ever find an ideal solution, but we need to start with something.

Unless you have more arguments or concerns to share @rec25, please approve the PR.

**Comment by rec25** [comment]
I don't mind modules based architecture. There are a few things I have discussed to know how to manage them.

We are able to move forward for sure.

**Review by rec25 — APPROVED** [review]

**Pull request merged**
